// CATEGORIES
export const categories = [
  { id: 1, name: "Men's Wear", image: "https://picsum.photos/400?random=101", color: "bg-blue-100 text-blue-700" },
  { id: 2, name: "Women's Wear", image: "https://picsum.photos/400?random=102", color: "bg-pink-100 text-pink-700" },
  { id: 3, name: "Kids Wear", image: "https://picsum.photos/400?random=103", color: "bg-yellow-100 text-yellow-700" },
  { id: 4, name: "Electronics", image: "https://picsum.photos/400?random=104", color: "bg-purple-100 text-purple-700" },
  { id: 5, name: "Footwear", image: "https://picsum.photos/400?random=105", color: "bg-green-100 text-green-700" },
  { id: 6, name: "Accessories", image: "https://picsum.photos/400?random=106", color: "bg-red-100 text-red-700" },
  { id: 7, name: "Beauty & Grooming", image: "https://picsum.photos/400?random=107", color: "bg-purple-100 text-purple-700" },
  { id: 8, name: "Home Decor", image: "https://picsum.photos/400?random=108", color: "bg-orange-100 text-orange-700" },
  { id: 9, name: "Kitchen", image: "https://picsum.photos/400?random=109", color: "bg-teal-100 text-teal-700" },
  { id: 10, name: "Bags", image: "https://picsum.photos/400?random=110", color: "bg-gray-100 text-gray-700" },
  { id: 11, name: "Watches", image: "https://picsum.photos/400?random=111", color: "bg-indigo-100 text-indigo-700" },
  { id: 12, name: "Sports", image: "https://picsum.photos/400?random=112", color: "bg-lime-100 text-lime-700" }
];


// PRODUCTS  
export const products = [
  {
    id: 1,
    name: "Classic Denim Jacket",
    price: 1499,
    category: "Men's Wear",
    image: "https://picsum.photos/400?random=201",
    description: "Premium quality denim with a stylish modern fit.",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Floral Summer Dress",
    price: 999,
    category: "Women's Wear",
    image: "https://picsum.photos/400?random=202",
    description: "Beautiful floral print perfect for summer outings.",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Kids Cotton T-shirt",
    price: 399,
    category: "Kids Wear",
    image: "https://picsum.photos/400?random=203",
    description: "Soft and breathable cotton fabric for kids.",
    rating: 4.6,
  },
  {
    id: 4,
    name: "Smart Bluetooth Watch",
    price: 1999,
    category: "Electronics",
    image: "https://picsum.photos/400?random=204",
    description: "Fitness tracking + notification alerts.",
    rating: 4.5,
  },
  {
    id: 5,
    name: "Running Shoes",
    price: 1299,
    category: "Footwear",
    image: "https://picsum.photos/400?random=205",
    description: "Lightweight running shoes for everyday use.",
    rating: 4.4,
  },
  {
    id: 6,
    name: "Leather Wallet",
    price: 499,
    category: "Accessories",
    image: "https://picsum.photos/400?random=206",
    description: "Premium leather with multiple compartments.",
    rating: 4.6,
  },
  {
    id: 7,
    name: "Makeup Kit Pro",
    price: 1499,
    category: "Beauty & Grooming",
    image: "https://picsum.photos/400?random=207",
    description: "Full essential makeup kit with high pigment.",
    rating: 4.9,
  },
  {
    id: 8,
    name: "Abstract Wall Painting",
    price: 799,
    category: "Home Decor",
    image: "https://picsum.photos/400?random=208",
    description: "High-quality frame with vibrant abstract art.",
    rating: 4.7,
  },
  {
    id: 9,
    name: "Stainless Steel Cookware",
    price: 1199,
    category: "Kitchen",
    image: "https://picsum.photos/400?random=209",
    description: "Durable steel cookware set for modern kitchens.",
    rating: 4.5,
  },
  {
    id: 10,
    name: "Trendy Shoulder Bag",
    price: 899,
    category: "Bags",
    image: "https://picsum.photos/400?random=210",
    description: "Stylish and spacious for everyday outings.",
    rating: 4.6,
  },
  {
    id: 11,
    name: "Digital Sports Watch",
    price: 699,
    category: "Watches",
    image: "https://picsum.photos/400?random=211",
    description: "Shock-resistant with premium digital display.",
    rating: 4.3,
  },
  {
    id: 12,
    name: "Football Size 5",
    price: 499,
    category: "Sports",
    image: "https://picsum.photos/400?random=212",
    description: "Strong stitching + durable long-life material.",
    rating: 4.5,
  },
];
